services:
  api:
    build:
      context: .
      dockerfile: docker/dockerfile-api
    container_name: api
    hostname: api
    networks:
      - hokse-ai-network
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "$API_PORT:$API_PORT"
    environment:
      - API_HOST
      - API_PORT
      - LOG_LEVEL
      - NOSQL_DB_HOST
      - NOSQL_DB_PORT
      - NOSQL_DB_USER
      - NOSQL_DB_PASSWORD
      - NOSQL_DB_NAME
      - LLM_PROVIDER
      - LLM_MODEL
      - LLM_API_KEY
      - LLM_HOST
      - LLM_PORT
      - STRAVA_CLIENT_ID
      - STRAVA_CLIENT_SECRET
      - STRAVA_OAUTH_URL
      - STRAVA_TOKEN_URL
      - STRAVA_API_URL
      - STRAVA_REDIRECT_URI
      - STRAVA_SCOPE
      - UI_HOST
      - UI_PORT

  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    hostname: mongodb
    networks:
      - hokse-ai-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${NOSQL_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${NOSQL_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${NOSQL_DB_NAME}
    ports:
      - "$NOSQL_DB_PORT:$NOSQL_DB_PORT"
    volumes:
      - ./mongodb_data:/data/db
    healthcheck:
      test: >
        mongosh mongodb:27017/test
        -u ${NOSQL_DB_USER}
        -p ${NOSQL_DB_PASSWORD}
        --authenticationDatabase admin
        --quiet
        --eval "db.runCommand({ ping: 1 }).ok"
      interval: 5s
      timeout: 5s
      retries: 5
  ui:
    build:
      context: .
      dockerfile: docker/dockerfile-ui
    container_name: ui
    hostname: ui
    networks:
      - hokse-ai-network
    depends_on:
      - api
    ports:
      - "$UI_PORT:$UI_PORT"
    environment:
      - UI_HOST
      - UI_PORT
      - API_HOST=api
      - API_PORT
      - API_PUBLIC_URL=http://localhost:${API_PORT}

networks:
  hokse-ai-network:
    driver: bridge
    name: hokse-ai-network
